DROP TABLE BO.EMPRUNTS CASCADE CONSTRAINTS;
DROP TABLE BO.LIVRES CASCADE CONSTRAINTS;

DROP TABLE BO.AUTEURS CASCADE CONSTRAINTS;
DROP TABLE BO.GENRES CASCADE CONSTRAINTS;
DROP TABLE BO.SECTIONS CASCADE CONSTRAINTS;
DROP TABLE BO.MEMBRES CASCADE CONSTRAINTS;