--------------------------------------------------------
--  DDL pour Table Membres
-- PRENOM,NOM,GENRE,DATE_NAISSANCE,COURRIEL,ADRESSE_LIGNE1,ADRESSE_LIGNE2,VILLE,PROVINCE,CODE_POSTAL,PAYS,TELEPHONE,DATE_DEBUT_MEMBRE,STATUT_MEMBRE,THEME_PREFERE
--------------------------------------------------------
CREATE Table BO.MEMBRES (
    id              NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 ),
    code            CHAR(12) UNIQUE,
    PRENOM          VARCHAR2(50) NOT NULL,
    NOM             VARCHAR2(50) NOT NULL,
    GENRE           CHAR(1),
    DATE_NAISSANCE  DATE,
    COURRIEL        VARCHAR2(50) NOT NULL,
    ADRESSE_LIGNE1  VARCHAR2(50),
    ADRESSE_LIGNE2  VARCHAR2(50),
    VILLE           VARCHAR2(50) DEFAULT 'Québec',
    PROVINCE        VARCHAR2(50) DEFAULT 'Québec',
    CODE_POSTAL     VARCHAR2(50),
    PAYS            VARCHAR2(50) DEFAULT 'Canada',
    TELEPHONE       VARCHAR2(50),
    DATE_DEBUT_MEMBRE DATE,
    STATUT_MEMBRE VARCHAR2(50),
    THEME_PREFERE VARCHAR2(50)   
);
COMMENT ON TABLE BO.MEMBRES IS
    'Table qui illustre un membre de la blibliotheque';

    
--------------------------------------------------------
--  DDL pour Table Sections
--------------------------------------------------------
CREATE TABLE BO.SECTIONS (
    id               NUMBER PRIMARY KEY,
    nom              VARCHAR2(50) NOT NULL,
    description      VARCHAR2(255) NOT NULL
);

COMMENT ON TABLE BO.SECTIONS IS 'Table des sections physiques de la bibliothèque.';

--------------------------------------------------------
--  DDL pour Table Genre
--------------------------------------------------------
CREATE TABLE BO.GENRES (
    genres_id        NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 ),
    nom_genre VARCHAR2(50) NOT NULL
);

COMMENT ON TABLE BO.GENRES IS 'Table des genres littéraires';


--------------------------------------------------------
--  DDL for Table Auteur
--------------------------------------------------------
CREATE TABLE BO.AUTEURS (
    auteurs_id                        NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 ),
    nom_auteur             VARCHAR2(100) NOT NULL
);
COMMENT ON TABLE BO.AUTEURS IS
    'Table qui gére la liste des clients';

--------------------------------------------------------
--  DDL pour Table Livre
-- sections_id, auteurs_id, genres_id, isbn, titre, maison_edition, annee_publication, langage, prix
--------------------------------------------------------
CREATE TABLE BO.LIVRES (
    livres_id    NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 ),
    sections_id  NUMBER(3) NOT NULL,
    auteurs_id   NUMBER NOT NULL,
    genres_id    NUMBER NOT NULL,
    isbn        VARCHAR2(50) NOT NULL,
    titre       VARCHAR2(100) NOT NULL,
    maison_edition  VARCHAR2(50),
    annee_publication NUMBER(4),
    langage           VARCHAR2(50),
    prix        NUMBER(5,2)
);

COMMENT ON TABLE BO.LIVRES IS 'Table des livres .';


--------------------------------------------------------
--  DDL pour la table emprunt
-- LIVRES_ID,MEMBRES_ID,DATE_EMPRUNT,DATE_RETOUR
--------------------------------------------------------
CREATE TABLE BO.EMPRUNTS (
-- identifiant Unique de emprunt qui est incrémenté de 1 a chaque nouveau(clée primaire)
    id_emprunt      NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 ),
-- identifiant du livre de l'emprunt, clée secondaire
    livres_id        NUMBER NOT NULL,
-- identifiant du membre associé a l'emprunt, clée secondaire
    membres_id       NUMBER NOT NULL,
-- Date a la quelle l'emprunt a été fait
    date_emprunt    DATE DEFAULT SYSDATE NOT NULL,
-- Date a la quelle l'emprunt devrait etre de retour (21 jours plus tard)
    date_retour_prevu GENERATED ALWAYS AS (date_emprunt + 21) VIRTUAL,
-- Date a la quelle le livre est vraiment revenu
    date_retour     DATE
);

COMMENT ON TABLE BO.EMPRUNTS IS 'Table des emprunts effectués .';

-- Clee Primaire et secondaire


-- Clee primaire table membre
AlTER TABLE BO.MEMBRES
    ADD CONSTRAINT MEMBRES_PK PRIMARY KEY (id);


-- Clee primaire de emprunts

ALTER TABLE BO.EMPRUNTS
    ADD CONSTRAINT EMPRUNTS_PK PRIMARY KEY (id_emprunt);


-- Clee primaire de livre

ALTER TABLE BO.LIVRES
    ADD CONSTRAINT LIVRES_PK PRIMARY KEY (livres_id);

-- Clee primaire de auteur

ALTER TABLE BO.AUTEURS
    ADD CONSTRAINT AUTEUR_PK PRIMARY KEY (auteurs_id);

-- Clee primaire de sections

ALTER TABLE BO.SECTIONS
    ADD CONSTRAINT SECTIONS_PK  PRIMARY KEY (id);

-- Clee primaire de sections

ALTER TABLE BO.GENRES
    ADD CONSTRAINT GENRES_PK PRIMARY KEY (genres_id);



-- Liaison LIVRES à SECTIONS
ALTER TABLE BO.LIVRES
  ADD CONSTRAINT LIVRES_FK_SECTION
  FOREIGN KEY (sections_id)
  REFERENCES BO.SECTIONS(id)
  ENABLE;

-- Liaison LIVRES à AUTEURS
ALTER TABLE BO.LIVRES
  ADD CONSTRAINT LIVRES_FK_AUTEUR
  FOREIGN KEY (auteurs_id)
  REFERENCES BO.AUTEURS(auteurs_id)
  ENABLE;

-- Liaison LIVRES à GENRES
ALTER TABLE BO.LIVRES
  ADD CONSTRAINT LIVRES_FK_GENRE
  FOREIGN KEY (genres_id)
  REFERENCES BO.GENRES(genres_id)
  ENABLE;

-- Liaison EMPRUNTS a LIVRES
ALTER TABLE BO.EMPRUNTS
  ADD CONSTRAINT EMPRUNTS_FK_LIVRE FOREIGN KEY (livres_id)
    REFERENCES BO.LIVRES(livres_id)
    ON DELETE CASCADE
    ENABLE;

-- Liaison EMPRUNTS a MEMBRES
ALTER TABLE BO.EMPRUNTS
  ADD CONSTRAINT EMPRUNTS_FK_MEMBRE FOREIGN KEY (membres_id)
    REFERENCES BO.MEMBRES(id)
    ON DELETE CASCADE
    ENABLE;




-- Création des contraintes spécifiques


-- Permet de mettre trois types de genre dans GENRE

ALTER TABLE BO.MEMBRES
    ADD CONSTRAINT MEMBRES_CHECK_GENRE CHECK (GENRE IN ('M','F','X'));


-- Permet d'avoir un format conventionnelle sur le téléphone

ALTER TABLE BO.MEMBRES
    ADD CONSTRAINT MEMBRES_CHECK_TEL CHECK (REGEXP_LIKE(TELEPHONE, '^\d{3}-\d{3}-\d{4}$'));

-- J'utilise un REGEX pour que le code soit entre 4 et 8 lettre

ALTER TABLE BO.MEMBRES
    ADD CONSTRAINT MEMBRES_CHECK_CODE CHECK (REGEXP_LIKE(CODE, '^[A-Z]{4}\d{8}$'));


-- J'utilise une contrainte comme dans genre pour donner trois options 

ALTER TABLE BO.MEMBRES
    ADD CONSTRAINT MEMBRES_CHECK_PAYS CHECK (PAYS IN ('Canada','États-Unis','Mexique'));




-- Création de la séquence

CREATE SEQUENCE BO.CODE_MEMBRE_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE;
/



